<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: Magiccart<team.magiccart@gmail.com>
 * @@Create Date: 2014-04-25 13:15:04
 * @@Modify Date: 2014-11-09 18:05:51
 * @@Function:
 */
?>

<?php

// drawMainHome
$menu = $this->cfgExt->topmenu;
if(!$menu['enabled']) return;
$drawHomeMenu = '';
$home = $menu['home'];
if($home){
	$this->drawHomeMenu();
	$drawHomeMenu   = Mage::registry('drawHomeMenu');  
}

// drawMainMenu vs DrowMobileMenu
$this->drawMainMenu();
$mobileMenu   = Mage::registry('mobileMenu');
$drawMainMenu = Mage::registry('drawMainMenu');

// drawExtMenu ExtraMenu
$drawExtraMenu = '';
$ext = $menu['extraCat'];
if($ext){
	$this->drawExtraMenu();
	$drawExtraMenu = Mage::registry('drawExtraMenu');
}

?>
<?php $sticker = $menu['sticker'] ? 'sticker' : ''; ?>
<div class="magicmenu clearfix">
	<ul class="nav-desktop <?php echo $sticker ?>">
		<?php echo $drawHomeMenu ?>
		<?php echo $menu['mainCat'] ? $drawMainMenu : '' ?>
		<?php echo $drawExtraMenu ?>
	</ul>
</div>
<div class="nav-mobile">
	<h3 class="mobi-title"><?php echo $this->__('Categories')?></h3>
	<ul>
		<?php echo $mobileMenu ?>
	</ul>
</div>
