<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<div class="blog-toolbar blog-toolbar-top">
   <?php echo $this->getChildHtml('blog_comments_toolbar'); ?>
</div>
<?php 
$_hpImages = Mage::helper('blog/images');
$width  = 871;
$height = 435;
?>
<?php foreach ($posts as $post): ?>
    <div class="postWrapper">
		<div class="post-img">
			<a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getImage() ? '<img  class="img-responsive" src="'. $_hpImages->resizeImg(basename($post->getImage()), $width, $height) .'">' : ''; ?></a>
			<div class="post-date-bottom">
				<?php $s = $post->getCreatedTime(); $date = strtotime($s); $date2 = strtotime($s); ?>
			   <span class="date-home-day"><?php echo date("d", $date) ?></span>
			   <span class="date-home-month"><?php echo date("M", $date2) ?></span>
			</div>
		</div>
        
		<div class="by post-date">
			<div class="postDetails">
				<?php if ($this->getCommentsEnabled()): ?>
					<?php //echo $post->getCommentCount(); ?> <!--<a href="<?php //echo $post->getAddress(); ?>#commentBox" > <?php //echo Mage::helper('blog')->__('Comments'); ?></a>-->
				<?php endif; ?>
				<?php $postCats = $post->getCats(); ?>
				<?php if (!empty($postCats)): ?>
					<?php //echo Mage::helper('blog')->__('Posted in'); ?>
					<?php foreach ($postCats as $data): ?>
						<!--<a href="<?php //echo $data['url']; ?>"><?php //echo $data['title']; ?></a>-->
					<?php endforeach; ?>
				<?php else: ?>
					<?php //echo Mage::helper('blog')->__('Posted'); ?>
				<?php endif; ?><i class="fa fa-user"></i><?php echo $this->__("By:"); ?> <span class="user"><?php echo $post->getUser(); ?></span>
			</div>
			<div class="number"><i class="fa fa-calendar-o"></i><span><?php echo $post->getCreatedTime(); ?></span></div>
			<i class="fa fa-comment-o"></i><span class="comments"><?php echo $post->getCommentCount().' '. $this->__('comments') ?></span>
		</div>
		<div class="postTitle">
            <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
        </div>
		<!--<div class="tags"><?php //echo $this->getTagsHtml($post) ?></div>-->
		<?php echo $this->getBookmarkHtml($post) ?>
        <div class="postContent"><?php echo $post->getPostContent(); ?></div>
    </div>
<?php endforeach; ?>
<div class="blog-toolbar blog-toolbar-bottom">
<?php echo $this->getChildHtml('blog_comments_toolbar'); ?>
</div>
