<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: Magiccart<team.magiccart@gmail.com>
 * @@Create Date: 2014-04-25 13:15:04
 * @@Modify Date: 2014-12-02 13:58:14
 * @@Function:
 */
?>

<?php

// drawMainHome
$menu = $this->cfgExt->vmenu;
if(!$menu['enabled']) return;
$drawHomeMenu = '';
$home = $menu['home'];
if($home){
	$this->drawHomeMenu();
	$drawHomeMenu   = Mage::registry('drawHomeMenu');  
}

// drawMainMenu vs DrowMobileMenu
$this->drawMainMenu();
$drawMainMenu = Mage::registry('drawMainMenu');

// drawExtMenu ExtraMenu
$drawExtraMenu = '';
$ext = $menu['extraCat'];
if($ext){
	$this->drawExtraMenu();
	$drawExtraMenu = Mage::registry('drawExtraMenu');
}
$rootName = Mage::getModel('catalog/category')->load(Mage::app()->getStore()->getRootCategoryId())->getName();
?>
<div class="vmagicmenu clearfix">
    <div class="block-title block-title-vmagicmenu">
        <strong>
            <span class="fa fa-bars"></span>
            <span class="vmagicmenu-subtitle"><?php echo $this->__($rootName); ?></span>
        </strong>
    </div>
	<ul class="vmagicmenu-narrow clearfix">
		<?php echo $drawHomeMenu ?>
		<?php echo $menu['mainCat'] ? $drawMainMenu : '' ?>
		<?php echo $drawExtraMenu ?>
	</ul>
</div>
<?php 
if($this->cfgExt->topmenu['enabled']) return; 
$mobileMenu   = Mage::registry('mobileMenu');
?>
<div class="nav-mobile">
	<ul>
		<?php echo $mobileMenu ?>
	</ul>
</div>

